# syntax=docker/dockerfile:1
FROM --platform=$BUILDPLATFORM python:3.9.4-alpine AS build

WORKDIR /code/app

COPY requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY /app /code/app

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--reload"]
